import Head from 'next/head'

const contact = () => {
    return ( 
        <>
        <head>
            <title>facebook | contact us </title>
            <meta name="descrptopn" content='Generated by create next app' />
            <link rel="icon" href="/favicon.ico" />
        </head>
        <h1>Contact Us</h1>
        <style jsx> {`
        h1 {
            color: black;
            display: flex;
            justify-content: center;

        }`
    }
        </style>
        </>
     );
}
 
export default contact;